### ISSUE TITLE
Set application window's dimensions and position with OSC

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#10]
It's useful to have it in OSC for 2 reasons (that I can think of and that I have used in previous iterations):

1. the position of the window on startup can be put in a `startup.cvs` script file.  There can be many for different setups (single vs multiple displays).
2. it can be used to live code the window, making it part of the performance, for example shaking it with a loop that sets it's position at random every 0.1 seconds (I can't think of any other performance uses, but this one is worth it).

**Comment by totalgee** [comment]
Related: the workspace should also either scale-to-fit (scale at draw time, without changing the stage size) or actually resize when the window is resized. Not sure which of these is most useful

**Comment by loopier** [comment]
> Related: the workspace should also either scale-to-fit (scale at draw time, without changing the stage size) or actually resize when the window is resized. Not sure which of these is most useful

Maybe we should open a new issue for this.
The original demand has been solved in 1147cdd0729ad8d0b3d39d21a93af16a4782e81a
