### ISSUE TITLE
Implement config system

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#12]
The config system can be built with OSC messages that are called at startup.  Things that it should handle (extend as needed in this thread?):

- custom paths for `commands/` and `assets/`with default to the current ones (or application's default directory).  Maybe they should have an order of preference (user-defined overwrites app-defaults if present)?
- maybe a "project" file with a list of assets and commands to be used?  Not sure if this is the same as the previous point.
- application window placement (#10)
- server IP address and port

**Comment by totalgee** [comment]
> The config system can be built with OSC messages that are called at startup.

What do you mean "can be built with OSC messages"? Wouldn't this be a "config file" that would be read from disk at startup? Can you give an example (commands) of what you mean?

You mean something like `/config/animpath dir`? What would that do, save the config to disk for subsequent runs, or only affect the current state?

**Comment by loopier** [comment]
> You mean something like `/config/animpath dir`?

yes.  Having a bunch of config OSC messages to config stuff in the app.
Saving these in a file as we do custom `/defs` it's like a config file.  The app just needs to call this "script" at startup.  Does it make sense?

This allow for runtime configuration, and avoids having to setup a dedicated parsing system just for the config (with JSON or INI or whatever).  We have one parsing system to rule them all.

**Comment by totalgee** [comment]
Yes, makes sense, thanks. Would it always save the current settings on exit, or only explicitly when you call a save settings command?

**Comment by loopier** [comment]
not sure.  Automatic saving has the danger of accidentally overwriting files.

Another question might be what config file does it load by default?  The last one used?

**Comment by loopier** [comment]
A first implementation in 1147cdd0729ad8d0b3d39d21a93af16a4782e81a saves config files as regular `/defs` in `res://config/`.

The workflow is the same as  with custom commands, so the config file has to be loaded AND executed.

An example config file named `config.osc`:
```
def /config
    /window/screen 1
    /window/fullscreen
```
would be used with
```
n.sendMsg("/load/config", "config.osc");
n.sendMsg("/config");
```

**Comment by loopier** [comment]
Is it possible/desirable to read OSC commands directly from a file without putting them in a `def`?
```
/window/screen 1
/window/fullscreen
```
as opposed to
```
def /config
    /window/screen 1
    /window/fullscreen
```

**Comment by totalgee** [comment]
I added some fixes to your work on this, so now it basically works:

- Fix a few minor things with config code: 133a247
- Load config.osc by default and run /config (if available): 48206f8

I don't know if having to define a `/config` message is the best way, but it's fine for now. In fact, with the current approach, we don't really need a `$Config.loadConfig()` (`/load/config`) method (and associated OSC command), since it's basically identical to `$OscInterface.loadDefsFile()` (`/load/defs`). On startup, for loading the default config file, we could just call `$CustomCommands.loadCommandFile()` and then run `/config`.

**Comment by loopier** [comment]
You're right, I could've just remapped with OSC.  Let's remove it.

**Comment by totalgee** [comment]
I added a new config option to allow you to restrict OSC messages from non-localhost clients:

- Add `/app/remote` configuration command (to block remote) 7cf6879
