### ISSUE TITLE
Workspace resizing when window size changes

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#13]
_Opening a dedicated threat for a request related to #10 and originally posted there._

The workspace should also either scale-to-fit (scale at draw time, without changing the stage size) or actually resize when the window is resized. Not sure which of these is most useful

**Comment by totalgee** [comment]
Resolved by:

- Implement `/window/size` command e874d34

The viewport/content size is fixed (currently at 1024x600), but it scales to fit any size window, and and the aspect ratio is maintained (with black letterboxing on the sides or top/bottom as needed).
