### ISSUE TITLE
Add `/quit` command

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#15]
It would be nice to have a `/quit` command to stop the server remotely.

**Comment by totalgee** [comment]
Out of curiosity...why?

**Comment by loopier** [comment]
1. why not :)
2. when using one display with fullscreen, there's no way to quit it (the linux shortcut `ctr + [q|w]` didn't work- which we may also have to add).  Actually there is a way of quitting, sending a `/fullscreen false`, and then closing the app, but its one more step :) 
Not at all urgent.

**Comment by totalgee** [comment]
BTW on Windows, the usual Alt-F4 does close it even when fullscreen.

I usually map Esc to go out of fullscreen mode, when I write apps. (Or 'f' to toggle fullscreen on and off)

I still don't see why this is a good thing to be able to do this OSC, it's just asking for trouble if the public can send messages to your server, ha ha...

**Comment by loopier** [comment]
oook.  Let's drop it :)
