### ISSUE TITLE
Relative command arguments

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#35]
How about adding some syntax to command arguments to make them relative to the current value?
A possible syntax:
`/position anactor +0.1 0.5` would move `0.1` to the right on the `x` axis and set the `y` value to absolute `0.5` (like it currently does).

**Comment by totalgee** [comment]
How would you handle negative values? Is the `-` a relative prefix or just a negative value? It would maybe be better to have an explicit prefix, like `r0.1 0.5`.

**Comment by loopier** [comment]
The explicit prefix feels a bit odd to me. Some other ideas:

- an address suffix like `/position/add`, or `/position/+`, or `/position/relative`, ...?

- If we use an explicit prefix, I'd maybe add a `:` inbetween, like `r:0.1 0.5`.

- Or maybe we can use just another command, like `/move`, `/shrink`, ...

**Comment by loopier** [comment]
How about using nouns for absolute parameters, and verbs for relative? For example:

- `/rotation target 45` would set the angle to 45 degrees
- while `/rotate target 45` would increase the current angle by 45 degrees

I would just  implement one command and function in **GDScript**, something like
`/relative target cmd args`

Then we could create `defs` for all the verbs with something like
```
/def /rotate target degs
     /relative $target /rotation $degs 
```
This might limit this "algorithm" to one-argument commands, but I'm starting to see a pattern where one-argument commands can be combined also in `defs` to get multiple-argument commands.

Other noun/verb pairs could be:

- `/scale`: `/increase`, `/decrease`; or `/grow`, `/shrink`
- `/position`: `/move`
- `/color`: `/paint`-- not at all sure about this one, maybe `/colorize`
- `/opacity`: `/fade`
- `/front`, `/behind`: `/rise`, `/lower` -- this doesn't make sense because the arguments are other clips, not numbers
- `...`: `/flip[h|v]`

**Comment by totalgee** [comment]
We can debate specific examples for different properties, but as a general rule I like your noun/verb absolute/relative idea.

However, I don't understand what you mean about the `/relative` OSC command, and how it relates to the others (or why it's required).

**Comment by loopier** [comment]
The idea is to implement **only one OSC command**, in GDSscript, for relative parameters. Something like
```
/relative actor:s cmd:s arg:f
```
So if the user needs to increase the size of an actor named `om` by `0.1`, they would send
```
/relative om /scale 0.1
```
This would be a universal command that could be used with any attribute.
Then we could define the `verb` versions of the attributes with something like:
```
/def /increase actor amount
    /relative $actor /scale $amount

/def /move actor xamount yamount
    /relative $actor /position $xamount $yamount

....
``` 
The advantage here is that on the Godot and GDScript side, we only need to implement **one** new function and command, not one for every verb.

Does it make sense?

**Comment by totalgee** [comment]
It kind of makes sense, but whether it's an OSC command or not, the GDScript code still has to be written to know that `/relative` and then `/scale` needs to get the current scale, then apply a relative calculation, and then set the new actual scale.

Also, I find it a bit weird that the command would be `/relative` first, it seems backwards to my way of thinking (scale is more important than relative to me, relative is like a modifier). Bur I do understand that it simplifies things in one sense.

**Comment by loopier** [comment]
yes, it's not a very intuitive syntax, but it's consistent with the "commands call other commands" way of doing stuff. I totally agree with you, though.

As for the GDScript code that needs to be written to get the actual state of the attribute: that's precisely my point, doing it for **every** atribute seems a bit too much. Writing a universal version implies that there's some kind of dictionary, though. If we name the command addresses as the GDScript attributes, we might be able to map it directly, maybe? Not sure about this

**Comment by totalgee** [comment]
Regarding a lookup/dictionary to do getting/setting in a generic way, should also consider that the relative values for some params may not be additive, but multiplicative. Like scale makes sense to go down by 0.7x or up by 1.4x, rather than -0.3 or +0.4. But for the majority of parameters, additive makes sense (position, 2D rotation), but things like scaling or colour have other "relative" possibilities that may make more sense for them. The same applies to mixing/interpolating parameters...

**Comment by loopier** [comment]
Any suggestion on how to approach this?

**Comment by loopier** [comment]
Relative values added in https://github.com/loopier/animatron/commit/95baecd27cd48b2ae0fa8ce8f1331c43e2316d6a for:

-  absolute: `/postition` - relative: `/move`
-  absolute: `/angle` - relative: `/rotate`
-  absolute; `/size` - relative: `/scale`

I didn't see any other commands that my need relative values, so I'm closing the issue. If some more come up, we can reopen it or implement them.
