### ISSUE TITLE
Should we move the documentation to the Wiki?

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#40]
Do you reckon it would be a good idea to move the documentation (Reference.md) to the Wiki?

**Comment by totalgee** [comment]
I like Markdeep docs because it has expanded functionality over regular (or GitHub-flavoured) Markdown and can be viewed live in any browser, but if you prefer the Wiki approach I don't mind.

**Comment by loopier** [comment]
What extra functionality does it have?

**Comment by totalgee** [comment]
Lots of convenience and beautifying things.. Detailed here:

https://casual-effects.com/markdeep/

**Comment by loopier** [comment]
I see.

Then maybe we should just move all the info in the wiki to different `.md` docs in the `/docs` directory?

**Comment by totalgee** [comment]
No, feel free to use the Wiki, it's fine with me.

**Comment by loopier** [comment]
I'd rather have all the info in one place. I'm OK with multiple files in the `docs` directory
