### ISSUE TITLE
Code Editor

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#47]
A TextEdit node has been added in https://github.com/loopier/animatron/commit/5d49804ad7c7c03f5d52184714da919cdde2291b.

It's a very basic text editor that sends OSC messages. I thought it might be useful for users who want to quickly start using it. There's a separate repo with the stand-alone version of  this, but I reckoned having all in one place is more convenient.

To use it, just type any command and args (without commas) and press CTRL+ENTER for sending the current line or the selection.

It can be toggled with CTRL+E (for E-ditor).

**Comment by loopier** [comment]
I've seen that the `/error/reply` is inside a static func, while the `/status/reply` isn't. What's the reason? Printing to the post window from static funcs it's not easy.

I'm adding a post window and I was thinking on printing the `/reply` messages in it.

**Comment by totalgee** [comment]
A static method has no state, it is like a pure function. I probably just made some methods that had no dependencies (like helpers to calculate something) static. If you need to access a member, feel free to make the necessary ones non-static.

**Comment by loopier** [comment]
I see. But did you have something in mind when deciding to make one static and the other one not?

**Comment by loopier** [comment]
I changed `reportError` to a non-static func in https://github.com/loopier/animatron/commit/f99341f934c10862aed6617270922099b2c86c78. Tried it a little bit (sorry I'm not doing proper testing) and doesn't seem to brake anything. As non-static we can have the call to OSC sending error and post window printing in the same place. It avoids verbosity of posting calls.

**Comment by totalgee** [comment]
Sounds good (I've not tried it), thanks!
