### ISSUE TITLE
Polish `/create`

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#8]
`/create` now loads a movie, plays it, and places it at a random spot.
I'm not sure about doing all at once.  We definitely need a way to create an actor without showing it or playing it.  Here's a list of possible commands:

- `/new NAME ANIMATION` : create an instance of actor, not visible, not playing, positioned at center of stage.

Then all the following can be done with `/defs`:
- `/create NAME ANIMATION` : create an instance and display it.  Stopped.  Positioned at center of stage by default.
- `/createAt NAME ANIMATION X Y` : like `/create` but with a given position (maybe as optional parameters of `/create`?)
- `/createAndPlay NAME ANIMATION` : like `/create` but playing it.
- `/createRand NAME` : create an instance, play it and position it randomly.

**Comment by totalgee** [comment]
We can just change `/create` to not position it randomly, and not start playing, no? (we don't also need `/new`, do we?)

I agree the others can be done by "defs", in the init file for example. We might add a basic set of defs that we will "always" want... But for now, we can just work on our own set, as we see what's necessary?

We don't have a notion of "not visible" (except for `fade` 0). I think it's fine to have `/create` make a visible instance (or switch the anim for an existing instance, as it does now). When it is actually creating a new instance, then it shouldn't be playing, and should be at the centre of the stage.

**Comment by loopier** [comment]
We do need a way to create instances without them being visible at creation time.  So we can load actors with fade in, rescaling, repositioning.  I've tried it and you can see the transformations with:
```
def /arlequins
    /load arlequins
    /free *
    /newarlequi arlequi 0.2 2
    /newarlequi arleque 0.4 3
    /newarlequi arlecom 0.6 4
    /newarlequi arlequan 0.8 0
    /newarlequi arleon 1.0 1

def /newarlequi name pos frame
    /create $name arlequins
    /select $name
    /fade! 0
    /position! $pos 1.5
    /scale! 0.5 0.5
    /stop!
    /deselect!
```

**Comment by totalgee** [comment]
It seems to be related to selection? I don't see any flashing if I do this:

```
def /newarlequi name pos frame
    /create $name arlequins
    /fade $name 0
    /position $name $pos 0.5
    /scale $name 0.5 0.5
    /stop $name
```

**UPDATE:** Okay, I do see it if I run it many times (with `/free *` in between)...once in a while it you'll see a big version of the actor before it scales down and is faded out.

**Comment by totalgee** [comment]
With 544c3a0 I've fixed the above-mentioned issue, so for now we can leave `/create` as it is, and if you make instant changes to the fading, position, scale or rotation, those are taken into account immediately and there are no occasional single-frame glitches. We can possibly close this, because everything else can be done by custom command definition (create at centre, create hidden, etc.). Unless you have any problems with creating and then stopping it.
