### ISSUE TITLE
Find the proper way to load single-image assets

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#9]
Single image assets must now be 1-frame animations.
That seems a bit overkill.
It'd be nice to be able to discern between animations and single-image files.

**Comment by totalgee** [comment]
Maybe an `/images` directory?

**Comment by totalgee** [comment]
Do you prefer an `/images` directory, or should we change it so if you have files that are named `filename.png` (or whatever extension) without any metadata after a `_`, then those are considered single images? (currently if you don't provide metadata, the default is a 4x4 spritesheet at 24fps...kind of arbitrary, but that was the format of the first images you provided me. ;-) We could change it, so for spritesheets you always have to use the `name_NxM_Ffps.png` convention. Or, a new command that would load as single images...

**Comment by loopier** [comment]
my experience is that the simpler to use the better.  So I guess I'd go for letting Animatron decide if it's a single image or a sequence.Actually, an image is a 1-frame sequence, I think it's good practice to treat it as such.  What are your thoughts on this?

**Comment by totalgee** [comment]
> So I guess I'd go for letting Animatron decide if it's a single image or a sequence.

Meaning what? "Yes" to changing the interpretation of image files without `_...` metadata?

**Comment by totalgee** [comment]
Resolved by:

- Images without "metadata" (underscores) default to single-frame 712ef4a
